spring:
  application:
    name: z-customer-data-service

  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    password: apppass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none   # or update (dev only)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8082

security:
  api-key: dev-api-key

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.shawn.customer: DEBUG